latest version

diff --git a/rsync-backup b/rsync-backup
--- a/rsync-backup
+++ b/rsync-backup
@@ -1,47 +1,50 @@
 #!/bin/sh
 
-## == RELEASE NOTES =============================================== ##
-##:2013-04-22:0.0.0:go2null
-## * initial release
-##
-##:2013-04-24:0.1.0:go2null
-## * Changed shell from bash to sh, as is POSIX compliant
-##
-##:2013-04-25:0.2.0:go2null
-## * NEW: Added options to autoremove oldest backups if free space (KB or %) falls below either minimum
-## * NEW: Added MAX # backups to keep
-##
-##:2013-05-06:0.3.0:go2null
-## * NEW: Creates a 'previous' symlink, allow other backup scripts to use a rsync --link-dest
-##
-##:2013-05-07:0.4.0:go2null
-## * FIX: BAK_SPACE_MB was calculated incorrectly
-## * NEW: Added output INFO messages
-## * NEW: checks free space after backup
+# == RELEASE NOTES =============================================== #
+VERSION=2013-04-22:0.0.0:go2null
+# * initial release
+VERSION=2013-04-24:0.1.0:go2null
+# * Changed shell from bash to sh, as is POSIX compliant
+VERSION=2013-04-25:0.2.0:go2null
+# * NEW: Added options to autoremove oldest backups if free space (KB or %) falls below either minimum
+# * NEW: Added MAX # backups to keep
+VERSION=2013-05-06:0.3.0:go2null
+# * NEW: Creates a 'previous' symlink, allow other backup scripts to use a rsync --link-dest
+VERSION=2013-05-07:0.4.0:go2null
+# * FIX: BAK_SPACE_MB was calculated incorrectly
+# * NEW: Added output INFO messages
+# * NEW: checks free space after backup
+VERSION=2013-05-28:0.5.0:go2null
+# * FIX:  bug #31746#note-3 in directory listing (no code change)
+VERSION=2013-06-11:0.6.0:go2null
+# * NEW:  option for MIN_KB/MIN_% to override KEEP_MIN to allow backups even with critically low free space
+# * FIX:  directory to backup - leaf directory repeated. Need to append '/'.
+# * FIX:  # backups check always return 0
+# * FIX:  If PTN not defined, rsync copies PWD as well as source.
+VERSION=2013-09-16:0.7.0:go2null
+# * NEW:  split out user settings into .conf file
+# * NEW:  all options can be specified as input parameters
 
-## == USER SETTINGS =============================================== ##
-BAK_DIR='/var/backups'
-## Num backups to keep, more will be deleted automatically if free space falls below MIN_KB or MIN_%
-BAK_KEEP_MIN=8
-BAK_KEEP_MAX=32
-BAK_SPACE_MB_MIN=10000
-BAK_SPACE_PC_MIN=5
-## path of directories and files to backup
-BAK_1='/etc/apache2/ports.conf'
-BAK_2='/etc/apache2/sites-available/rdq3'
-BAK_3='/etc/apache2/ssl'
-PTN_3="--exclude='*.key' --include'*/' --exclude='*'"
-BAK_4='/etc/hosts'
-BAK_5='/etc/logrotate.conf'
-BAK_6='/etc/network/interfaces'
-BAK_7='/etc/resolv.conf'
-BAK_8='/etc/sudoers'
-BAK_11='/var/log'
-BAK_12='/etc/apt/sources.list'
-BAK_13='/etc/apt/apt.conf.d/99NoRecommends'
-BAK_14='/etc/fstab'
+# == FUNCTIONS =================================================== #
+printHelp() {
+printf %s "
+VERISION: $VERSION
+USAGE: $(basename -- "$0") -b DIRECTORY -k NUMBER -K NUMBER -s NUMBER -S NUMBER -o -f FILE
+OPTIONS:
+  -f FILE      - config file. Can be specified multiple times in order of increasing priority.
+  -d DIRECTORY - directory to backup to
+  -k NUMBER    - minimum backups to keep. Default is 1.
+  -K NUMBER    - maximum backups to keep.
+  -s NUMBER    - minimum free space to reserve, in MB.
+  -S NUMBER    - minimum free space to reserve, as %.
+  -o           - by default, -k is overridden when -s or -S is met.
+                 This option disables this behaviour. Impact is that the backup is not done.
+DESCRIPTION:
+* Creates "YYYY-MM-DD-HHMMSS" directories in BAK_DIR
+* Creates a 'latest' symlink, pointing to the backup made
+* Creates a 'previous' symlink, allow other backup scripts to use a rsync --link-dest
+"}
 
-## == FUNCTIONS =================================================== ##
 getFreeSpace() {
 	BAK_SPACE_MB=$(df -Pk "$BAK_DIR" | awk '!/Filesystem/ {print int($4/1024)}')
 	BAK_SPACE_PC=$(df -Pk "$BAK_DIR" | awk '!/Filesystem/ {print 100-$5}')
@@ -50,57 +53,85 @@ getFreeSpace() {
 pruneIfSpaceLow() {
 	getFreeSpace
 
-	## set IFS to newline, required for 'for' loops to parse DIR with space in names correctly
+	# set IFS to newline, required for 'for' loops to parse DIR with space in names correctly
 	IFS_PREV=$IFS
 	IFS="
 	"
-	while [ "$BAK_SPACE_MB" -lt "$BAK_SPACE_MB_MIN" ] || [ "$BAK_SPACE_PC" -lt "$BAK_SPACE_PC_MIN" ]; do
-		if [ "$1" = "before" -a "$BAK_CNT" -ge "$BAK_KEEP_MIN" ] || [ "$1" = "after" -a "$BAK_CNT" -gt "$BAK_KEEP_MIN" ]; then
-			## remove oldest, using 'for' as quick way to get DIR
-			for DIR in $(find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | sort -r); do
+	while [ "$BAK_SPACE_MB" -lt "$BAK_SPACE_MIN_MB" ] || [ "$BAK_SPACE_PC" -lt "$BAK_SPACE_MIN_PC" ]; do
+		if [ "$1" = "warn" ]; then
+			echo "INFO: Free space available:       $BAK_SPACE_PC % / $BAK_SPACE_MB MB"
+			echo 'WARNING: Free space on backup volume below minimums'
+			break
+		elif [ $BAK_MIN_OVERRIDE -eq 1 -a $BAK_CNT -gt 0 ] || [ "$BAK_CNT" -ge "$BAK_KEEP_MIN" ]; then
+			# remove oldest, using 'for' as quick way to get DIR
+			for DIR in $(find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '.*/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | sort -r); do
 				echo "INFO: Deleting to free up space: $DIR"
-				echo rm -rf "$DIR"
-				## just do 1st DIR in list (which is oldest as 'sort -r')
+				rm -rf "$DIR"
+				# just do 1st DIR in list (which is oldest as 'sort -r')
 				break
 			done
 		else
-			if [ "$1" = "after" ]; then
-				echo 'WARNING: Free space on backup volume below minimums'
-			else
-				echo "INFO: Free space available:       $BAK_SPACE_PC % / $BAK_SPACE_MB MB"
-				echo 'ERROR: Not enough free space on backup volume'
-				exit 1
-			fi
+			echo "INFO: Free space available:       $BAK_SPACE_PC % / $BAK_SPACE_MB MB"
+			echo 'ERROR: Not enough free space on backup volume'
+			exit 1
 		fi
 		: $((BAK_CNT-=1))
 		getFreeSpace
 	done
-	echo "INFO: Free space available:       $BAK_SPACE_PC % / $BAK_SPACE_MB MB"
-	## reset IFS
+	# reset IFS
 	IFS=$IFS_PREV
 }
 
-## == HEADER ==== ================================================= ##
-echo "INFO: Backup start time:          $(date +%Y-%m-%d\ %H:%M:%S)"
-echo "INFO: Backup directory:           $BAK_DIR"
+# == DEFAULT SETTINGS =============================================== #
+# Num backups to keep
+BAK_KEEP_MIN=1
+BAK_KEEP_MAX=999999999
+# Override KEEP_MIN if free space falls below MIN_KB or MIN_%
+BAK_MIN_OVERRIDE=1
 
-## == VALIDATIONS ================================================= ##
-[ -d "$BAK_DIR" ] || mkdir -p "$BAK_DIR"
-[ $? -gt 0 ] && { echo "ERROR: Invalid backup directory '$BAK_DIR'."; exit 1; }
-## if 'latest' is not a symlink, then it may be a file or dir, and so may have user data
-if [ -e "$BAK_DIR/latest" ]; then
-	[ -L "$BAK_DIR/latest" ] || { echo "ERROR: '$BAK_DIR/latest' should be a symlink to the last backup."; exit 1; }
+# == INPUT PARAMETERS =============================================== #
+# get
+while [ $# -gt 0 ]; do
+	case "$1" in
+		-f) { . "$2"; }            ;;
+		-d) BAK_DIR=$2             ;;
+		-k) BAK_KEEP_MIN=$2        ;;
+		-K) BAK_KEEP_MAX=$2        ;;
+		-s) BAK_SPACE_MIN_MB=$2    ;;
+		-S) BAK_SPACE_MIN_PC=$2    ;;
+		-o) unset BAK_MIN_OVERRIDE ;;
+	esac
+	shift
+done
+
+# == HEADER ==== ================================================= #
+echo "INFO: Backup start time:          $(date +%Y-%m-%d\ %H:%M:%S)"
+echo "INFO: Backup destination:         $BAK_DIR"
+echo "INFO: Min/Max backup to keep:     $BAK_KEEP_MIN/$BAK_KEEP_MAX"
+echo "INFO: Min free space:             $BAK_SPACE_MIN_MB MB/$BAK_SPACE_MIN_PC %"
+echo "INFO: Override min backups:       $BAK_MIN_OVERRIDE"
+
+# == VALIDATIONS ================================================= #
+if [ -z "$BAK_DIR" ] || { ! mkdir -p "$BAK_DIR"; } 2>/dev/null; then
+	{ echo "ERROR: Invalid backup directory '$BAK_DIR'. Exiting."; 
+	  exit 1; 
+	} >&2
+# if 'latest' is not a symlink, then it may be a file or dir, and so may have user data
+if [ -e "$BAK_DIR/latest" ] && [ ! -L "$BAK_DIR/latest" ]; then
+	{ echo "ERROR: '$BAK_DIR/latest' should be a symlink to the last backup.";
+	  exit 1; 
+	} >&2
 fi
 
-## == PRUNE OLD BACKUPS =========================================== ##
-## set IFS to newline, required for 'for' loops to parse DIR with space in names correctly
+# == PRUNE OLD BACKUPS =========================================== #
+# set IFS to newline, required for 'for' loops to parse DIR with space in names correctly
 IFS_PREV=$IFS
 IFS="
 "
-## prune (old) backups -gt BAK_KEEP_MAX
-BAK_CNT=$(   find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | wc -l)
+# prune (old) backups -gt BAK_KEEP_MAX
+BAK_CNT=$(   find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '.*/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | wc -l)
 echo "INFO: # backups, max/current/min: $BAK_KEEP_MAX / $BAK_CNT / $BAK_KEEP_MIN"
-for DIR in $(find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | sort -r); do
+for DIR in $(find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -regex '.*/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}' | sort -r); do
 	if [ "$BAK_CNT" -ge "$BAK_KEEP_MAX" ]; then
 		echo "INFO: Pruning old backup #$BAK_CNT: $DIR"
 		rm -rf "$DIR"
@@ -109,65 +140,74 @@ for DIR in $(find "$BAK_DIR" -mindepth 1 -maxdepth 1 -type d -regextype sed -reg
 	fi
 	: $((BAK_CNT-=1))
 done
-## reset IFS
+# reset IFS
 IFS=$IFS_PREV
 
-## prune (old) backup IF free space is low AND -gt BAK_KEEP_MIN
-echo "INFO: Free space minimums:        $BAK_SPACE_PC_MIN % / $BAK_SPACE_MB_MIN MB"
+# prune (old) backups IF free space is low
+echo "INFO: Free space minimums:        $BAK_SPACE_MIN_PC % / $BAK_SPACE_MIN_MB MB"
 pruneIfSpaceLow before
 
-## == CREATE DIRECTORY FOR CURRENT BACKUP ========================= ##
+# == CREATE DIRECTORY FOR CURRENT BACKUP ========================= #
 TIME_STAMP=$(date +%Y-%m-%d-%H%M%S)
 BAK_DEST_CURR=$BAK_DIR/$TIME_STAMP
 mkdir "$BAK_DEST_CURR" || { echo "ERROR: Cannot write to backup dir '$BAK_DIR'."; exit 1; }
 
-## == MAIN BACKUP ROUTINE ========================================= ##
+# == MAIN BACKUP ROUTINE ========================================= #
 COUNTER=1
 while true; do
         eval "BAK_SRCE_PATH=\$BAK_$COUNTER"
         eval "PTN=\$PTN_$COUNTER"
-        ## stop on 1st blank source
+        # stop on 1st blank source
         if [ -z "$BAK_SRCE_PATH" ]; then
-                echo "INFO: Backup complete"
+                echo && echo "INFO: Backup complete"
                 break
         else
-                echo "INFO: Backing up $BAK_SRCE_PATH"
-                ## ignore missing sources 
+                echo && echo "INFO: Backing up $BAK_SRCE_PATH"
+                # ignore missing sources 
                 if [ -e "$BAK_SRCE_PATH" ]; then
-                        ## added "/" before $BAK_SRCE_PATH to allow for relative source paths
-                        ##      the "//" in the result is handled correctly by mkdir, ln and rsync
+                        # added "/" before $BAK_SRCE_PATH to allow for relative source paths
+                        #      the "//" in the result is handled correctly by mkdir, ln and rsync
                         BAK_DEST_PATH="$BAK_DEST_CURR/$BAK_SRCE_PATH"
                         BAK_LINK_PATH="$BAK_DIR/latest/$BAK_SRCE_PATH"
 
-                        ## rsync does not create parent directories, only final target directory.
-                        ##      creating parent directory as the target may be a file.
+                        # rsync does not create parent directories, only final target directory.
+                        #      creating parent directory as the target may be a file.
                         BAK_DEST_PARENT=$(dirname -- "$BAK_DEST_PATH")
                         [ -e "$BAK_DEST_PARENT" ] || mkdir -p "$BAK_DEST_PARENT"
-                        [ -d "$BAK_DEST_PARENT" ] || { echo "WARNING: Bad destination, skipping."; continue; }
 
-                        ## rsync doesn't sync single files with --link-dest option
-                        ##      http://stackoverflow.com/questions/7100900/rsync-link-dest-option-for-single-file
-                        ##      https://bugzilla.samba.org/show_bug.cgi?id=8594
-                        if [ -f "$BAK_SRCE_PATH" ]; then
-                                ## as rsync creates a new file (inode), 
-                                ##      then the purpose of the ln is to create a target for rsync to minimize data transfer??
-                                [ -e "$BAK_LINK_PATH" ] && ln "$BAK_LINK_PATH"                         "$BAK_DEST_PATH"
-                                rsync -aP                                             "$BAK_SRCE_PATH" "$BAK_DEST_PATH"
-                        else
-                                rsync -aPx        --link-dest="$BAK_LINK_PATH" "$PTN" "$BAK_SRCE_PATH" "$BAK_DEST_PATH"
-                        fi
-			[ $? -gt 0 ] && echo "WARNING: error occured"
-                fi
+                        if [ -d "$BAK_DEST_PARENT" ]; then
+							# rsync doesn't sync single files with --link-dest option
+							#      http://stackoverflow.com/questions/7100900/rsync-link-dest-option-for-single-file
+							#      https://bugzilla.samba.org/show_bug.cgi?id=8594
+							if [ -f "$BAK_SRCE_PATH" ]; then
+								# as rsync creates a new file (inode), 
+								#      then the purpose of the ln is to create a target for rsync to minimize data transfer??
+								[ -e "$BAK_LINK_PATH" ] && ln "$BAK_LINK_PATH"                        "$BAK_DEST_PATH"
+								rsync -av                                            "$BAK_SRCE_PATH" "$BAK_DEST_PATH"
+							else
+								# if use "$PTN" and PTN is blank, 
+								#   rsync interprets the ("") as a period (.), and copies from current directory as well.
+								#   http://askubuntu.com/questions/112717/rsync-copies-files-from-working-directory-in-addition-to-the-requested-ones
+								rsync -avx        --link-dest="$BAK_LINK_PATH" $PTN "$BAK_SRCE_PATH" "$BAK_DEST_PATH"
+							fi
+							[ $? -gt 0 ] && echo "WARNING: error occured"
+						else
+							echo "WARNING: Bad destination, skipping."
+						fi
+				else
+					echo "WARNING: source doesn't exist, skipping."
+				fi
                 COUNTER=$(($COUNTER+1))
         fi
 done
 
-## == PRUNE OLD BACKUPS =========================================== ##
-## prune (old) backup IF free space is low AND -gt BAK_KEEP_MIN
-## main (only?) reason for running again is to provide a warning, that, in effect, the next backup will fail
-pruneIfSpaceLow after
+# == PRUNE OLD BACKUPS =========================================== #
+# prune (old) backup IF free space is low AND -gt BAK_KEEP_MIN
+# main (only?) reason for running again is to provide a warning, that, in effect, the next backup will fail
+pruneIfSpaceLow warn
 
-## == UPDATE SYMLINKS ============================================= ##
+# == UPDATE SYMLINKS ============================================= #
 rm "$BAK_DIR/previous"                         || echo "WARNING: Cannot remove '$BAK_DIR/previous' symlink."
 mv "$BAK_DIR/latest" "$BAK_DIR/previous"       || echo "WARNING: Cannot update '$BAK_DIR/previous symlink."
 ln -s "$BAK_DIR/$TIME_STAMP" "$BAK_DIR/latest" || { echo "ERROR: Cannot update '$BAK_DIR/latest' symlink."; exit 1; }
+
